[package]
name = "desktop_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.1"
souvlaki = "0.6.1"
raw-window-handle = "0.5.2"
egui = "0.22.0"
serde_json = "1.0"
rdev = "0.5.3"